version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: areus
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  areus-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: areus-app
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/areus
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345678
    networks:
      - default

volumes:
  mysql_data: